name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy the demo site to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install

      - name: Build
        run: yarn demo:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./demo
