name: tests
on: [push, pull_request]
jobs:
  lint-and-test:
    name: Lint and run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install

      - name: Check for lint errors
        run: yarn lint

      - name: Run tests
        if: success()
        run: yarn test
